# -*- coding: utf-8 -*-
"""Bank Authentication.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jkPWBfU2fAnpKSIpDmWU46FHHJnD0bMz

Indra Niko Saputra - 24060120130091
"""

#Import Library
import pandas as pd
import pickle

#Import dataset beserta melihat 5 data teratas
dataset = pd.read_csv('./BankNote_Authentication.csv')
dataset.head()

f1 = int(input())
f2 = int(input())

#Fitur 3 dan 4
#petal_length dan petal_width
X= dataset.iloc[:, [f1,f2]].values

#Membuat Model menggunakan KMeans dengan elbow method
#Inisialisasi menggunakan metode kMeans++
import sklearn
from sklearn.cluster import KMeans
wcss=[]

#Cluster yang diperkirakan sampai 20 cluster
for i in range(1,10):
    kmeans = KMeans(n_clusters= i, init='k-means++', random_state=42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

    #inertia_ digunakan untuk memisah data menjadi sebuah cluster

import matplotlib.pyplot as plt

# membuat elbow method dengan range cluster sampai 20
plt.plot(range(1,10), wcss)
plt.title('The Elbow Method')
plt.xlabel('no of clusters')
plt.ylabel('wcss')
elbow_figure = plt.show()

k = int(input())

#Dari grafik terlihat bahwa sudut siku sekitar pada k=3

#Fitting Model
kmeansmodel = KMeans(n_clusters= k, init='k-means++', random_state=0)
y_kmeans= kmeansmodel.fit_predict(X)

colname = list(dataset.columns)

#Visualisasi Kluster

clr = ['red','yellow','blue','green','pink','cyan','magenta','orange','black','purple']
for i in range(k):
  plt.scatter(X[y_kmeans == i, 0], X[y_kmeans == i, 1], s = 30, c = clr[i], label = f'Cluster {i+1}')
plt.title('Clusters IRIS')
plt.xlabel(colname[f1])
plt.ylabel(colname[f2])
plt.legend()
plt.show()